# Generated by Django 2.1 on 2020-07-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField()),
                ('user_type', models.CharField(max_length=255)),
                ('profile_image', models.URLField()),
                ('display_name', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.CharField(max_length=255)),
                ('view_count', models.IntegerField()),
                ('closed_date', models.DateField()),
                ('answer_count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('last_activity_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('question_id', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('closed_reason', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
