# Generated by Django 2.1 on 2020-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_activity_date',
            field=models.DateTimeField(),
        ),
    ]
