# Generated by Django 2.1 on 2020-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200724_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='search_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
