# Generated by Django 2.1 on 2020-07-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
