# Generated by Django 2.1 on 2020-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200725_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
